# SPDX-License-Identifier: AGPL-3.0-only
"""Helpers for PR score diffs in GitHub Action comments."""

from __future__ import annotations

import json
from pathlib import Path

COMMENT_MARKER = "<!-- rade-pr-score-comment -->"
TRACKED_SCORES = ("reusability", "accessibility_risk")


def load_report(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def extract_score(report: dict, score_name: str) -> int:
    return int(report["scores"][score_name]["value"])


def build_score_diff(base_report: dict, head_report: dict) -> dict[str, dict[str, int]]:
    diff: dict[str, dict[str, int]] = {}
    for score_name in TRACKED_SCORES:
        base_value = extract_score(base_report, score_name)
        head_value = extract_score(head_report, score_name)
        diff[score_name] = {
            "base": base_value,
            "head": head_value,
            "delta": head_value - base_value,
        }
    return diff


def _format_delta(delta: int) -> str:
    if delta > 0:
        return f"+{delta}"
    return str(delta)


def render_pr_comment(
    diff: dict[str, dict[str, int]],
    base_ref: str,
    head_ref: str,
    gate_status: str = "disabled",
) -> str:
    lines = [
        COMMENT_MARKER,
        "## RADE score diff",
        "",
        f"Compared `{base_ref}` -> `{head_ref}`.",
        f"Regression gate status: `{gate_status}`.",
        "Direction: higher `reusability` is better; lower `accessibility_risk` is better.",
        "",
        "| Metric | Base | Head | Delta |",
        "|---|---:|---:|---:|",
    ]
    for score_name in TRACKED_SCORES:
        values = diff[score_name]
        lines.append(
            f"| `{score_name}` | {values['base']} | {values['head']} | {_format_delta(values['delta'])} |"
        )
    lines.extend(
        [
            "",
            "_Generated by RADE GitHub Action._",
        ]
    )
    return "\n".join(lines)


def has_score_regression(diff: dict[str, dict[str, int]]) -> bool:
    """Regression rule: reusability down OR accessibility risk up."""
    return diff["reusability"]["delta"] < 0 or diff["accessibility_risk"]["delta"] > 0
